spring:
  application:
    name: BeBiS
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:postgresql://localhost:5432/bebis_db
    username: bebis_user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          blizzard-service: # Client Credentials Flow
            provider: blizzard
            client-id: ${BLIZZARD_CLIENT_ID}
            client-secret: ${BLIZZARD_CLIENT_SECRET}
            authorization-grant-type: client_credentials
          blizzard-user: # Authorization Code Flow
            provider: blizzard
            client-id: ${BLIZZARD_CLIENT_ID}
            client-secret: ${BLIZZARD_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: wow.profile

        provider:
          blizzard:
            authorization-uri: https://oauth.battle.net/authorize
            token-uri: https://oauth.battle.net/token
            user-info-uri: https://eu.battle.net/oauth/userinfo
            user-name-attribute: sub

blizzard:
  api:
    locale: en_GB
    namespace:
      header: Battlenet-Namespace
      user: profile-classic1x-eu
      service: static-classic1x-eu
    base-url: https://eu.api.blizzard.com

resilience4j:
  circuitbreaker:
    instances:
      blizzardFetcher:
        register-health-indicator: true

logging:
  level:
    org.springframework.security: TRACE
    com.bebis.BeBiS: DEBUG
