spring:
  application:
    name: BeBiS

  security:
    oauth2:
      client:
        registration:
          blizzard-service: # Client Credentials Flow
            provider: blizzard
            client-id: ${BLIZZARD_CLIENT_ID}
            client-secret: ${BLIZZARD_CLIENT_SECRET}
            authorization-grant-type: client_credentials
          blizzard-user: # Authorization Code Flow
            provider: blizzard
            client-id: ${BLIZZARD_CLIENT_ID}
            client-secret: ${BLIZZARD_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: wow.profile

        provider:
          blizzard:
            authorization-uri: https://oauth.battle.net/authorize
            token-uri: https://oauth.battle.net/token
            user-info-uri: https://openid-connect.onboard.battle.net/userinfo

blizzard:
  api:
    locale: en_GB
    namespace:
      header: Battlenet-Namespace
      client: profile-eu
      service: static-classic1x-eu
    base-url: https://eu.api.blizzard.com

logging:
  level:
    com.bebis.BeBiS: DEBUG
