spring.application.name=BeBiS

# OAuth2 #
spring.security.oauth2.client.registration.blizzard.client-id=${BLIZZARD_CLIENT_ID}
spring.security.oauth2.client.registration.blizzard.client-secret=${BLIZZARD_CLIENT_SECRET}
spring.security.oauth2.client.registration.blizzard.authorization-grant-type=client_credentials

spring.security.oauth2.client.provider.blizzard.token-uri=https://oauth.battle.net/token