-- 1. Independent Tables
CREATE TABLE wow_characters
(
    blizzard_account_id BIGINT       NOT NULL,
    id                  BIGINT       NOT NULL,
    realm_slug          VARCHAR(255) NOT NULL,
    level               INTEGER,
    name                VARCHAR(255) NOT NULL,
    race                VARCHAR(255) NOT NULL,
    realm_name          VARCHAR(255) NOT NULL,
    wow_class           VARCHAR(255) NOT NULL,
    PRIMARY KEY (blizzard_account_id, id, realm_slug)
);

CREATE TABLE items
(
    item_category   VARCHAR(31)  NOT NULL,
    base_id         BIGINT       NOT NULL,
    suffix_id       BIGINT       NOT NULL,
    armor_value     INTEGER,
    inventory_type  VARCHAR(255) NOT NULL,
    item_level      INTEGER,
    name            VARCHAR(255) NOT NULL,
    quality         VARCHAR(255) NOT NULL,
    required_level  INTEGER,
    unique_equipped BOOLEAN,
    armor_type      VARCHAR(255),
    dps             DOUBLE PRECISION,
    max_damage      INTEGER,
    min_damage      INTEGER,
    speed           DOUBLE PRECISION,
    weapon_type     VARCHAR(255),
    PRIMARY KEY (base_id, suffix_id)
);

-- 2. Tables with Foreign Keys to Level 1
CREATE TABLE character_equipment
(
    blizzard_account_id BIGINT       NOT NULL,
    character_id        BIGINT       NOT NULL,
    realm_slug          VARCHAR(255) NOT NULL,
    PRIMARY KEY (blizzard_account_id, character_id, realm_slug),
    CONSTRAINT fk_char_equip_to_char
        FOREIGN KEY (blizzard_account_id, character_id, realm_slug)
            REFERENCES wow_characters (blizzard_account_id, id, realm_slug)
);

CREATE TABLE item_effects
(
    base_id            BIGINT NOT NULL,
    suffix_id          BIGINT NOT NULL,
    effect_description VARCHAR(1000),
    CONSTRAINT fk_item_effects_to_items
        FOREIGN KEY (base_id, suffix_id)
            REFERENCES items (base_id, suffix_id)
);

CREATE TABLE item_stats
(
    base_id    BIGINT       NOT NULL,
    suffix_id  BIGINT       NOT NULL,
    stat_value INTEGER,
    stat_type  VARCHAR(255) NOT NULL,
    PRIMARY KEY (base_id, suffix_id, stat_type),
    CONSTRAINT fk_item_stats_to_items
        FOREIGN KEY (base_id, suffix_id)
            REFERENCES items (base_id, suffix_id)
);

-- 3. Tables with Foreign Keys to Level 2
CREATE TABLE equipped_items
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    base_id       BIGINT       NOT NULL,
    suffix_id     BIGINT       NOT NULL,
    owner_account BIGINT       NOT NULL,
    owner_id      BIGINT       NOT NULL,
    owner_realm   VARCHAR(255) NOT NULL,
    slot_name     VARCHAR(255),
    CONSTRAINT fk_equipped_to_char_equip
        FOREIGN KEY (owner_account, owner_id, owner_realm)
            REFERENCES character_equipment (blizzard_account_id, character_id, realm_slug),
    CONSTRAINT fk_equipped_to_items
        FOREIGN KEY (base_id, suffix_id)
            REFERENCES items (base_id, suffix_id)
);

-- 4. Tables with Foreign Keys to Level 3
CREATE TABLE player_enchants
(
    equipped_item_id       BIGINT NOT NULL,
    enchant_display_string VARCHAR(500),
    CONSTRAINT fk_player_enchants_to_equipped
        FOREIGN KEY (equipped_item_id)
            REFERENCES equipped_items (id)
);